# Generated by Django 4.0.1 on 2022-02-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('phone_manufacturer', models.CharField(max_length=200)),
                ('phone_model', models.CharField(max_length=200)),
                ('screen_height', models.IntegerField()),
                ('screen_width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oculid.tester')),
            ],
        ),
        migrations.CreateModel(
            name='picx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField()),
                ('pic_num', models.IntegerField(unique=True)),
                ('image_path', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='iamges/')),
                ('base64_image', models.TextField()),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oculid.tester')),
            ],
        ),
    ]
