# Generated by Django 4.0.1 on 2022-02-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oculid', '0002_alter_picx_base64_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picx',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='picx',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
